# baseURL: 'https://fahnestockj.com'
languageCode: en-us
title: Jacob Fahnestock
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 50
        menu:
            main:
                - name: Portfolio
                  url: portfolio
                  weight: 50
                - name: Resume
                  url: "/fahnestockj_cv.pdf"
                  weight: 50




params:
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        buttons: 
            - name: Portfolio
              url: "/portfolio"
            - name: Resume
              url: "/fahnestockj_cv.pdf"

        enabled: true
        title: Jacob Fahnestock
        imageUrl: "https://climapp.nyc3.digitaloceanspaces.com/headshots/headshot.jpg"
        imageTitle: profilephoto
        subtitle: Founding Software Engineer at **[Quanta](https://quantamarkets.com)**
    homeInfoParams:
        Title: "Jacob Fahnestock"
        Content: Founding Software Engineer at Quanta
    socialIcons:
        - name: github
          url: "https://github.com/fahnestockj"
        - name: linkedin
          url: "https://www.linkedin.com/in/fahnestockj/"
        - name: email
          url: "mailto:jrfz31@gmail.com"
   


    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     goldmark:
#         renderer:
#             unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: true
        simple: true

    x:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true